# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=80)),
                ('plan', models.TextField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trips',
            name='tripplanner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userplanner', to='buddy_app.Users'),
        ),
        migrations.AddField(
            model_name='trips',
            name='usertrip',
            field=models.ManyToManyField(related_name='travelbud', to='buddy_app.Users'),
        ),
    ]
